export const COVID_CASES_REQUEST = 'COVID_CASES_REQUEST'
export const COVID_CASES_SUCCESS = 'COVID_CASES_SUCCESS'
export const COVID_CASES_FAIL = 'COVID_CASES_FAIL'
export const COVID_CASES_RESET = 'COVID_CASES_RESET'